name: build-hook

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.0.0
        with:
          token: ${{ secrets.FOR_REPOSITORY_DISPATCH }}
          repository: KaterynaKupava/Test-for-Githubactions
          event-type: my-event
          #
          

      
