name: ci

on:
 workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker build
        run: |
             docker build -t python-test . 
             docker login -u katerynalymar -p ${{ secrets.DOCKERHUB_TOKEN }}
             docker tag python-test:latest katerynalymar/python-test:123
             docker push katerynalymar/python-test:123

