
name: Docker Image CI

on:
  workflow_dispatch:



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Docker Login
       # You may pin to the exact commit or the version.
        # uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
      uses: docker/login-action@v1.14.1
      with:
          # Username used to log against the Docker registry
          username: katerynalymar
          # Password or personal access token used to log against the Docker registry
          password: ${{ github.DOCKER_LOGIN }}

    

    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
      uses: docker/build-push-action@v2.10.0
      with:
        # Path to the Dockerfile
        #file: # optional
        # Push is a shorthand for --output=type=registry
        push: true

        # List of tags
        tags: 12

        github-token: ${{ github.DOCKER_LOGIN }}
